// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSSQhT-wnWZSTV1QrW_3_SzPBZ1qi4Q1U',
    appId: '1:409357940412:web:c0544f9efc8922ca4a82b9',
    messagingSenderId: '409357940412',
    projectId: 'clutterzap-f7e95',
    authDomain: 'clutterzap-f7e95.firebaseapp.com',
    databaseURL: 'https://clutterzap-f7e95-default-rtdb.firebaseio.com',
    storageBucket: 'clutterzap-f7e95.firebasestorage.app',
    measurementId: 'G-XPB37T4BZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaVhxCXTM9x_s4tF22obz1Rwhea923zk4',
    appId: '1:409357940412:android:ba5b6848a2f31b4d4a82b9',
    messagingSenderId: '409357940412',
    projectId: 'clutterzap-f7e95',
    databaseURL: 'https://clutterzap-f7e95-default-rtdb.firebaseio.com',
    storageBucket: 'clutterzap-f7e95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_ckCJ2MjScJgJzAwXVGblH1zqo7WxU0U',
    appId: '1:409357940412:ios:60343a799d5b88d94a82b9',
    messagingSenderId: '409357940412',
    projectId: 'clutterzap-f7e95',
    databaseURL: 'https://clutterzap-f7e95-default-rtdb.firebaseio.com',
    storageBucket: 'clutterzap-f7e95.firebasestorage.app',
    iosBundleId: 'com.example.clutterZap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_ckCJ2MjScJgJzAwXVGblH1zqo7WxU0U',
    appId: '1:409357940412:ios:60343a799d5b88d94a82b9',
    messagingSenderId: '409357940412',
    projectId: 'clutterzap-f7e95',
    databaseURL: 'https://clutterzap-f7e95-default-rtdb.firebaseio.com',
    storageBucket: 'clutterzap-f7e95.firebasestorage.app',
    iosBundleId: 'com.example.clutterZap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSSQhT-wnWZSTV1QrW_3_SzPBZ1qi4Q1U',
    appId: '1:409357940412:web:0f3f1faeb34340fc4a82b9',
    messagingSenderId: '409357940412',
    projectId: 'clutterzap-f7e95',
    authDomain: 'clutterzap-f7e95.firebaseapp.com',
    databaseURL: 'https://clutterzap-f7e95-default-rtdb.firebaseio.com',
    storageBucket: 'clutterzap-f7e95.firebasestorage.app',
    measurementId: 'G-5026SEQP1T',
  );

}